const sidebar = [
	{
		item_name: 'Accountant',
		icon: <i className="fa-solid fa-money-check-dollar"></i>,
		path: 'accountant',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'Salary',
				icon: '-',
				path: 'accountant/salary',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Stock',
				icon: '-',
				path: 'accountant/stock',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Warehouse',
				icon: '-',
				path: 'accountant/warehouse',
				has_children: true,
				children_item: [
					{
						item_name: 'Material',
						icon: '+',
						path: 'accountant/warehouse/material',
						has_children: false,
						children_item: [],
					},
				],
			},
		],
	},
	{
		item_name: 'Host',
		icon: <i className="fa-solid fa-user"></i>,
		path: 'Host',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'Order list',
				icon: '-',
				path: 'host/order-list',
				has_children: false,
				children_item: [],
			},
		],
	},
	{
		item_name: 'Kitchen',
		icon: <i className="fa-solid fa-burger"></i>,
		path: 'Kitchen',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'Order list',
				icon: '-',
				path: 'kitchen/order-list',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Order detail',
				icon: '-',
				path: 'kitchen/order-detail',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Menu',
				icon: '-',
				path: 'kitchen/menu',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'New menu',
				icon: '-',
				path: 'kitchen/new-menu',
				has_children: false,
				children_item: [],
			},
		],
	},
	{
		item_name: 'Leader',
		icon: <i className="fa-solid fa-address-book"></i>,
		path: 'Leader',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'Today employee',
				icon: '-',
				path: 'leader/today-employee',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Problem',
				icon: '-',
				path: 'leader/problem',
				has_children: false,
				children_item: [],
			},
		],
	},
	{
		item_name: 'Manager',
		icon: <i className="fa-solid fa-user-tie"></i>,
		path: 'Manager',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'Account',
				icon: '-',
				path: 'manager/account',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Customer',
				icon: '-',
				path: 'manager/customer',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Employee',
				icon: '-',
				path: 'manager/employee',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Permission',
				icon: '-',
				path: 'manager/permission',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Report',
				icon: '-',
				path: 'manager/report',
				has_children: false,
				children_item: [],
			},
		],
	},
	{
		item_name: 'Marketing',
		icon: <i className="fa-solid fa-chart-simple"></i>,
		path: 'Marketing',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'Promortion',
				icon: '-',
				path: 'marketing/promotion',
				has_children: false,
				children_item: [],
			},
			{
				item_name: 'Voucher',
				icon: '-',
				path: 'marketing/voucher',
				has_children: false,
				children_item: [],
			},
		],
	},
	{
		item_name: 'Shipper',
		icon: <i className="fa-solid fa-motorcycle"></i>,
		path: 'Shipper',
		is_main: true,
		has_children: true,
		children_item: [
			{
				item_name: 'New order',
				icon: '-',
				path: 'shipper/new-order',
				has_children: false,
				children_item: [],
			},
		],
	},
];

export default sidebar;
